# Generated by Django 3.0.5 on 2020-04-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('words', models.IntegerField()),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('wordStr', models.CharField(max_length=100)),
                ('known', models.IntegerField()),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='languagelearning.Meaning')),
            ],
        ),
        migrations.AddField(
            model_name='meaning',
            name='relatedWords',
            field=models.ManyToManyField(related_name='_meaning_relatedWords_+', to='languagelearning.Word'),
        ),
    ]
