# Generated by Django 3.0.5 on 2020-04-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languagelearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='words',
        ),
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
        migrations.AddField(
            model_name='word',
            name='relatedTexts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='languagelearning.Text'),
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='relatedWords',
        ),
        migrations.AddField(
            model_name='meaning',
            name='relatedWords',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='languagelearning.Word'),
        ),
    ]
